### ISSUE TITLE
Pull Request #3 broke for me...

### ISSUE THREAD

**Issue by cstivers78** [sevlyar/go-daemon#4]
Everything was working until Pull Request #3 

I now get this:
```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x4c974e]

goroutine 1 [running]:
github.com/sevlyar/go-daemon.(*Context).child(0xc208032410, 0x0, 0x0)
        /root/.whitesands/src/github.com/sevlyar/go-daemon/daemon_posix.go:250 +0x35e
github.com/sevlyar/go-daemon.(*Context).Reborn(0xc208032410, 0x0, 0x0, 0x0)
        /root/.whitesands/src/github.com/sevlyar/go-daemon/daemon_posix.go:73 +0x7d
main.main()
```

I forked and revered the change, and it works now.

**Comment by mialinx** [comment]
Add empty credential in your Context as workaround Context{ Credential: {} }
